-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvP3bkZodkcbdkNCX
kEn9tyMBeTuJ3fW8gzCotGeyPfCgCgYIKoZIzj0DAQehRANCAATmBsOTQnMa3shb
ofbFDeEXcbsFRizSDexayd2tYiA6PWVoYWVcyJkAtJtkHR64YA/1xjIQxcT3g3eZ
0vYr6Ltm
-----END PRIVATE KEY-----