#!/usr/bin/env node
/**
 * setupMixpanelDashboard — one-shot script that creates 7 Insights reports
 * for the diagnostic launch dashboard per spec §16.
 *
 * Auth: Mixpanel Service Account (Basic auth).
 * Requires env vars:
 *   MIXPANEL_PROJECT_ID                — numeric project ID
 *   MIXPANEL_SERVICE_ACCOUNT_USERNAME  — service account username
 *   MIXPANEL_SERVICE_ACCOUNT_PASSWORD  — service account secret
 *
 * Run once to seed reports; then manually organise them into a dashboard
 * via Mixpanel UI (Dashboards > New dashboard > Add existing reports).
 */

'use strict';

require('dotenv').config();

const PROJECT_ID = process.env.MIXPANEL_PROJECT_ID;
const SA_USER    = process.env.MIXPANEL_SERVICE_ACCOUNT_USERNAME;
const SA_PASS    = process.env.MIXPANEL_SERVICE_ACCOUNT_PASSWORD;

const INSIGHTS_API = 'https://mixpanel.com/api/app/workspaces/0/reports';

// ---------------------------------------------------------------------------
// Report definitions — 7 success metrics per spec §16
// ---------------------------------------------------------------------------

const REPORTS = [
  {
    name: 'Diagnostic Activation Rate',
    description: 'Share of registered users who start at least one diagnostic session.',
    type: 'insights',
    params: {
      chart_type: 'line',
      metric: {
        math: 'dau',
        event_selectors: [{ event: 'diagnostic_started' }],
      },
      date_range: { type: 'last', value: 30, unit: 'day' },
    },
  },
  {
    name: 'D1 Retention — Post-Diagnostic',
    description: 'Percentage of users who return on Day 1 after completing a diagnostic.',
    type: 'insights',
    params: {
      chart_type: 'line',
      metric: {
        math: 'retention',
        first_event: { event: 'diagnostic_completed' },
        return_event: { event: 'app_open' },
        retention_type: 'n_day',
        retention_n: 1,
      },
      date_range: { type: 'last', value: 30, unit: 'day' },
    },
  },
  {
    name: 'Time to Plan (p50 latency)',
    description: 'Median seconds from diagnostic_completed to plan_generated.',
    type: 'insights',
    params: {
      chart_type: 'line',
      metric: {
        math: 'median',
        property: '$duration',
        event_selectors: [{ event: 'plan_generated' }],
      },
      date_range: { type: 'last', value: 30, unit: 'day' },
    },
  },
  {
    name: 'Plan Engagement — Card Interactions',
    description: 'Total plan_card_tapped events; proxy for plan engagement.',
    type: 'insights',
    params: {
      chart_type: 'line',
      metric: {
        math: 'total',
        event_selectors: [{ event: 'plan_card_tapped' }],
      },
      date_range: { type: 'last', value: 30, unit: 'day' },
    },
  },
  {
    name: 'Sentiment Proxy — Topic Card Expand',
    description: 'Users who expand a topic card at least once (positive signal).',
    type: 'insights',
    params: {
      chart_type: 'line',
      metric: {
        math: 'dau',
        event_selectors: [{ event: 'topic_card_expanded' }],
      },
      date_range: { type: 'last', value: 30, unit: 'day' },
    },
  },
  {
    name: 'Calibration Coverage — LLM vs Template',
    description: 'Breakdown of plan_generated by generation_mode property (llm vs template).',
    type: 'insights',
    params: {
      chart_type: 'bar',
      metric: {
        math: 'total',
        event_selectors: [{ event: 'plan_generated' }],
      },
      breakdowns: [{ property: 'generation_mode', type: 'string' }],
      date_range: { type: 'last', value: 30, unit: 'day' },
    },
  },
  {
    name: 'Coverage Misses — Top canonicalTargets',
    description: 'question_bank_lookup_miss events ranked by canonicalTarget property.',
    type: 'insights',
    params: {
      chart_type: 'bar',
      metric: {
        math: 'total',
        event_selectors: [{ event: 'question_bank_lookup_miss' }],
      },
      breakdowns: [{ property: 'canonicalTarget', type: 'string' }],
      date_range: { type: 'last', value: 30, unit: 'day' },
    },
  },
];

// ---------------------------------------------------------------------------
// API call
// ---------------------------------------------------------------------------

async function createReport(report) {
  if (!PROJECT_ID || !SA_USER || !SA_PASS) {
    throw new Error(
      'Missing env vars: MIXPANEL_PROJECT_ID, MIXPANEL_SERVICE_ACCOUNT_USERNAME, MIXPANEL_SERVICE_ACCOUNT_PASSWORD'
    );
  }

  const credentials = Buffer.from(`${SA_USER}:${SA_PASS}`).toString('base64');

  const body = {
    name: report.name,
    description: report.description,
    type: report.type,
    params: report.params,
    project_id: Number(PROJECT_ID),
  };

  const res = await globalThis.fetch(INSIGHTS_API, {
    method: 'POST',
    headers: {
      Authorization: `Basic ${credentials}`,
      'Content-Type': 'application/json',
      Accept: 'application/json',
    },
    body: JSON.stringify(body),
  });

  const json = await res.json().catch(() => ({}));

  if (!res.ok) {
    throw new Error(
      `Mixpanel API error ${res.status} for "${report.name}": ${JSON.stringify(json)}`
    );
  }

  return json;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log(`Creating ${REPORTS.length} Mixpanel Insights reports for project ${PROJECT_ID}...\n`);

  let created = 0;
  for (const report of REPORTS) {
    try {
      const result = await createReport(report);
      const reportId = result.id || result.report_id || '(unknown id)';
      console.log(`  ✓ ${report.name}  (id: ${reportId})`);
      created++;
    } catch (err) {
      console.error(`  ✗ ${report.name}: ${err.message}`);
    }
  }

  console.log(`\nDone. ${created}/${REPORTS.length} reports created.`);
  if (created < REPORTS.length) {
    console.log('Some reports failed. Fix errors above and re-run; Mixpanel will deduplicate by name.');
    process.exit(1);
  }
  console.log('Next step: open Mixpanel > Dashboards > New dashboard, then add these reports.');
}

main().catch(e => { console.error(e); process.exit(1); });
